2025-08-02 20:03:45,577 ERROR root Uncaught exception:
Traceback (most recent call last):
  File "C:\Users\nicks\IdeaProjects\MoneySmarts_newVER\main.py", line 63, in main
    gui_manager.run()
  File "C:\Users\nicks\IdeaProjects\MoneySmarts_newVER\moneySmarts\ui.py", line 199, in run
    self.current_screen.handle_events(events)
  File "C:\Users\nicks\IdeaProjects\MoneySmarts_newVER\moneySmarts\screens\game_screen.py", line 513, in handle_events
    super().handle_events(events)
  File "C:\Users\nicks\IdeaProjects\MoneySmarts_newVER\moneySmarts\ui.py", line 126, in handle_events
    action()
  File "C:\Users\nicks\IdeaProjects\MoneySmarts_newVER\moneySmarts\screens\game_screen.py", line 388, in quit_game
    self.game.quit()
AttributeError: 'Game' object has no attribute 'quit'
